name: 'Dev Pipeline'

on:
  push:
    branches:
      - dev
      - new-project-structure

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WALLET_CONNECT_PROJECT_ID: ${{ secrets.WALLET_CONNECT_PROJECT_ID }}
  ONE_INCH_DEV_PORTAL_HOST: ${{ vars.ONE_INCH_DEV_PORTAL_HOST }}
  DAPP_IS_PRODUCTION: true

jobs:
  release:
    runs-on: macos-latest

    permissions:
      contents: write
      packages: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-environment
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Cache and Install Electron Dependencies
        uses: ./.github/actions/cache-electron-deps
        with:
          working-directory: apps/electron-dapp

      - name: Release
        run: npx semantic-release
        env:
          NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/apps/dapp
